/*

 * To change this license header, choose License Headers in Project Properties.

 * To change this template file, choose Tools | Templates

 * and open the template in the editor.

 */

package windows;



import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import rrhh.ConnectionDB;
import rrhh.Render;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */

public class ActiveUsersTable extends javax.swing.JPanel {

    /**

     * Creates new form ActiveUsersTable

     */

    public ActiveUsersTable() {
        initComponents();
        CargarTabla();
    }

    


    
    public void CargarTabla(){
        actUsTa.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = (DefaultTableModel) actUsTa.getModel();
        actUsTa.setRowHeight(20);
        //Comienza a contar 0 los renglones
        modelo.setRowCount(0);
        
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();

        ResultSet res = ConnectionDB.Query("SELECT * FROM users WHERE active_us = 1"); 
        try{
            while(res.next()){
                JButton btnDelete = new JButton("Delete");
                btnDelete.setBackground(Color.red);
                btnDelete.setName("btnDelete");

                JButton btnUpdate = new JButton("Update");
                btnUpdate.setBackground(Color.green);
                btnUpdate.setName("btnUpdate");

                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(btnDelete);
                v.add(btnUpdate);
                modelo.addRow(v);

                actUsTa.setModel(modelo);
            }
        }
        catch(SQLException e){

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {



        jLabel2 = new javax.swing.JLabel();

        jScrollPane1 = new javax.swing.JScrollPane();

        actUsTa = new javax.swing.JTable();



        setBackground(new java.awt.Color(102, 204, 255));

        setPreferredSize(new java.awt.Dimension(600, 290));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());



        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Active Users");

        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));



        actUsTa.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null},

                {null, null, null, null, null, null}

            },

            new String [] {

                "ID", "Username", "Password", "Role", "Delete", "Update"

            }

        ) {

            Class[] types = new Class [] {

                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class

            };

            boolean[] canEdit = new boolean [] {

                false, false, false, false, false, false

            };



            public Class getColumnClass(int columnIndex) {

                return types [columnIndex];

            }



            public boolean isCellEditable(int rowIndex, int columnIndex) {

                return canEdit [columnIndex];

            }

        });

        actUsTa.getTableHeader().setReorderingAllowed(false);

        actUsTa.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                actUsTaMouseClicked(evt);

            }

        });

        jScrollPane1.setViewportView(actUsTa);

        if (actUsTa.getColumnModel().getColumnCount() > 0) {

            actUsTa.getColumnModel().getColumn(0).setResizable(false);

            actUsTa.getColumnModel().getColumn(0).setPreferredWidth(4);

            actUsTa.getColumnModel().getColumn(1).setResizable(false);

            actUsTa.getColumnModel().getColumn(2).setResizable(false);

            actUsTa.getColumnModel().getColumn(3).setResizable(false);

            actUsTa.getColumnModel().getColumn(3).setPreferredWidth(15);

            actUsTa.getColumnModel().getColumn(4).setResizable(false);

            actUsTa.getColumnModel().getColumn(4).setPreferredWidth(10);

            actUsTa.getColumnModel().getColumn(5).setResizable(false);

            actUsTa.getColumnModel().getColumn(5).setPreferredWidth(10);

        }



        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 260));



        getAccessibleContext().setAccessibleName("");

    }// </editor-fold>//GEN-END:initComponents



    private void actUsTaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actUsTaMouseClicked

        int column = actUsTa.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/actUsTa.getRowHeight();

        if(row < actUsTa.getRowCount() && row >= 0 && column<actUsTa.getColumnCount() && column>=0){
            Object  value = actUsTa.getValueAt(row, column);
            Object id = actUsTa.getValueAt(row, 0);
            int id_User = (int) id;
            if(value instanceof JButton){
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("btnDelete")){
                    //Query para borrar
                    int option = JOptionPane.showConfirmDialog(null, "Do you really want to delete this user?", 
                            "Warning", JOptionPane.YES_NO_OPTION);
                    if(option == JOptionPane.YES_OPTION){
                        ConnectionDB con = new ConnectionDB();
                        con.deleteUserId(id_User);
                    }
                    CargarTabla();
                }
                else if(boton.getName().equals("btnUpdate")){
                    //query para modificar
                }
            }
        }
    }//GEN-LAST:event_actUsTaMouseClicked





    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTable actUsTa;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JScrollPane jScrollPane1;

    // End of variables declaration//GEN-END:variables

}



