/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.JOptionPane;
import rrhh.ConnectionDB;

/**
 *
 * @author Emmanuel
 */
public class AddUser extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    public AddUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        reEnterPassword = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        JLUsername = new javax.swing.JLabel();
        JLPassword = new javax.swing.JLabel();
        JLConPassword = new javax.swing.JLabel();
        roleList = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(710, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 300, 30));

        passwordField.setText("123");
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 300, 30));

        reEnterPassword.setText("321");
        add(reEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 300, 30));

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 150, -1));

        JLUsername.setText("Username");
        add(JLUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        JLPassword.setText("Password");
        add(JLPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        JLConPassword.setText("Confirm Password");
        add(JLConPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        roleList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROLE", "ADMINISTRATOR", "USER" }));
        roleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleListActionPerformed(evt);
            }
        });
        add(roleList, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 300, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void roleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleListActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        //Register new user
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();
        
        String username = this.Username.getText();
        String pass = new String(passwordField.getPassword());
        String cpass = new String(reEnterPassword.getPassword());
        String role = String.valueOf(this.roleList.getSelectedItem());
        boolean exists = conexion.existingUser(username);
        
        
        if(!username.equals("admin")){
            //Validate if the username already exists
            if(exists){
                //Create new user
                if(pass.equals(cpass)){
                    if(!role.equals("ROLE")){
                        conexion.createUser(username, pass, role);
                        JOptionPane.showMessageDialog(null, "Usuario creado");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Selecciona un Rol", null, JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", null, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLConPassword;
    private javax.swing.JLabel JLPassword;
    private javax.swing.JLabel JLUsername;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel image;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField reEnterPassword;
    private javax.swing.JButton register;
    private javax.swing.JComboBox<String> roleList;
    // End of variables declaration//GEN-END:variables
}
