/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rrhh.ConnectionDB;
import rrhh.Render;
import rrhh.Validations;
import static windows.menu.mainPanel;

/**
 *
 * @author Emmanuel
 */
public class Applicants extends javax.swing.JPanel {

    /**
     * Creates new form usersMenu
     */
    public Applicants() {
        initComponents();
        CargarTabla("SP_Search_Active_Users");
        
        
        
        
    }
    
    
    public void CargarTabla(String query){
        actUsTa.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = (DefaultTableModel) actUsTa.getModel();
        actUsTa.setRowHeight(20);
        //Comienza a contar 0 los renglones
        modelo.setRowCount(0);
        
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();

        ResultSet res = ConnectionDB.Query(query); 
        try{
            while(res.next()){
                JButton btnDelete = new JButton("Delete");
                btnDelete.setBackground(Color.red);
                btnDelete.setName("btnDelete");

                JButton btnUpdate = new JButton("Update");
                btnUpdate.setBackground(Color.green);   
                btnUpdate.setName("btnUpdate");
                
                JButton btnDeactivate = new JButton("Deactivate");
                btnDeactivate.setBackground(Color.BLUE);
                btnDeactivate.setName("btnDeactivate");
                
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(btnDelete);
                v.add(btnUpdate);
                v.add(btnDeactivate);
                modelo.addRow(v);

                actUsTa.setModel(modelo);
            }
        }
        catch(SQLException e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombre = new javax.swing.JTextPane();
        registerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        actUsTa = new javax.swing.JTable();
        buscarIdTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buscarID = new javax.swing.JButton();
        buscarNombreTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buscarNombre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showAllUsersBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        app = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        apm = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        expLab = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        expSal = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        puesto = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setBackground(new java.awt.Color(0, 204, 0));
        Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        Table.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(nombre);

        Table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 260, -1));

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        Table.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, -1, -1));

        actUsTa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido P", "Apellido M", "Experiencla Lab.", "Expectativa Salarial", "Puesto que aspira", "Delete", "Update", "HIre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        actUsTa.getTableHeader().setReorderingAllowed(false);
        actUsTa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actUsTaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(actUsTa);
        if (actUsTa.getColumnModel().getColumnCount() > 0) {
            actUsTa.getColumnModel().getColumn(0).setResizable(false);
            actUsTa.getColumnModel().getColumn(0).setPreferredWidth(10);
            actUsTa.getColumnModel().getColumn(1).setResizable(false);
            actUsTa.getColumnModel().getColumn(2).setResizable(false);
            actUsTa.getColumnModel().getColumn(3).setResizable(false);
            actUsTa.getColumnModel().getColumn(4).setResizable(false);
            actUsTa.getColumnModel().getColumn(5).setResizable(false);
            actUsTa.getColumnModel().getColumn(6).setResizable(false);
            actUsTa.getColumnModel().getColumn(7).setResizable(false);
            actUsTa.getColumnModel().getColumn(7).setPreferredWidth(10);
            actUsTa.getColumnModel().getColumn(8).setPreferredWidth(10);
            actUsTa.getColumnModel().getColumn(9).setPreferredWidth(10);
        }

        Table.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1210, 260));

        buscarIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdTxtActionPerformed(evt);
            }
        });
        buscarIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarIdTxtKeyPressed(evt);
            }
        });
        Table.add(buscarIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 196, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Buscar Candidato por ID");
        Table.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        buscarID.setText("Buscar");
        buscarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarIDMouseClicked(evt);
            }
        });
        Table.add(buscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        Table.add(buscarNombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Buscar Candidato por nombre");
        Table.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        buscarNombre.setText("Buscar");
        buscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarNombreMouseClicked(evt);
            }
        });
        Table.add(buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Candidatos Activos");
        Table.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        showAllUsersBtn.setText("Mostrar Todos");
        showAllUsersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllUsersBtnMouseClicked(evt);
            }
        });
        Table.add(showAllUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 120, -1));

        app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(app);

        Table.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 260, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Apellido Paterno");
        Table.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        apm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apmKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(apm);

        Table.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 260, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Apellido Materno");
        Table.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, -1));

        expLab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expLabKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(expLab);

        Table.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 260, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Experiencia  Laboral");
        Table.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        expSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expSalKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(expSal);

        Table.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 260, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Expectativa Salarial");
        Table.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, -1));

        puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                puestoKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(puesto);

        Table.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 260, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Puesto Deseado");
        Table.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char validate = evt.getKeyChar();

        if(!Character.isLetter(validate)){
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        //Register new user
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();

        String username = this.nombre.getText();
        
        boolean exists = conexion.existingUser(username);


    }//GEN-LAST:event_registerButtonActionPerformed

    private void actUsTaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actUsTaMouseClicked

        int column = actUsTa.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/actUsTa.getRowHeight();

        if(row < actUsTa.getRowCount() && row >= 0 && column<actUsTa.getColumnCount() && column>=0){
            Object  value = actUsTa.getValueAt(row, column);
            Object id = actUsTa.getValueAt(row, 0);
            int id_User = (int) id;
            if(value instanceof JButton){
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if(boton.getName().equals("btnDelete")){
                    //Query para borrar
                    int option = JOptionPane.showConfirmDialog(null, "Do you really want to delete this user?",
                        "Warning", JOptionPane.YES_NO_OPTION);
                    if(option == JOptionPane.YES_OPTION){
                        ConnectionDB con = new ConnectionDB();
                        con.deleteUserId(id_User);
                        CargarTabla("SP_Search_Active_Users");
                    }
                }
                else if(boton.getName().equals("btnUpdate")){
                    String nUsername = (String) actUsTa.getValueAt(row, 1);
                    String nPassword = (String) actUsTa.getValueAt(row, 2);
                    
                    ConnectionDB con = new ConnectionDB();
                    con.updateUser(nUsername, nPassword, id_User);
                    CargarTabla("SP_Search_Active_Users");
                    
                    JOptionPane.showMessageDialog(null, "User Updated");
                }
                else if(boton.getName().equals("btnDeactivate")){
                    //query desactivar user
                    int option = JOptionPane.showConfirmDialog(null, "Do you really want to deactivate this user?",
                        "Warning", JOptionPane.YES_NO_OPTION);
                    if(option == JOptionPane.YES_OPTION){
                        ConnectionDB con = new ConnectionDB();
                        con.changeStatus(id_User);
                        CargarTabla("SP_Search_Active_Users");
                        
                    }
                }
            }
        }
    }//GEN-LAST:event_actUsTaMouseClicked

    private void buscarIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarIdTxtActionPerformed

    private void buscarIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarIDMouseClicked

        int id_user = Integer.parseInt(buscarIdTxt.getText());
        String consulta = "SELECT * FROM users WHERE id_user = "+id_user;
        CargarTabla(consulta);
    }//GEN-LAST:event_buscarIDMouseClicked

    private void buscarIdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarIdTxtKeyPressed
       char validate = evt.getKeyChar();

    //        if(!Character.isDigit(validate)){
    //            getToolkit().beep();
    //            evt.consume();
    //            JOptionPane.showMessageDialog(null, "Ingresar solo números");
    //        }
    }//GEN-LAST:event_buscarIdTxtKeyPressed

    private void showAllUsersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllUsersBtnMouseClicked
        CargarTabla("SP_Search_Active_Users");
    }//GEN-LAST:event_showAllUsersBtnMouseClicked

    private void buscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarNombreMouseClicked
        String username = buscarNombreTxt.getText();
        String consulta = "SP_Search_User_Like '"+username+"'";
        
        buscarIdTxt.setText("");
        buscarNombreTxt.setText("");
        CargarTabla(consulta);
    }//GEN-LAST:event_buscarNombreMouseClicked

    private void appKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_appKeyTyped

    private void apmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apmKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_apmKeyTyped

    private void expLabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expLabKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_expLabKeyTyped

    private void expSalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expSalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_expSalKeyTyped

    private void puestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Table;
    private javax.swing.JTable actUsTa;
    private javax.swing.JTextPane apm;
    private javax.swing.JTextPane app;
    private javax.swing.JButton buscarID;
    private javax.swing.JTextField buscarIdTxt;
    private javax.swing.JButton buscarNombre;
    private javax.swing.JTextField buscarNombreTxt;
    private javax.swing.JTextPane expLab;
    private javax.swing.JTextPane expSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane nombre;
    private javax.swing.JTextPane puesto;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showAllUsersBtn;
    // End of variables declaration//GEN-END:variables
}
