/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import rrhh.ConnectionDB;
import rrhh.Render;
import rrhh.Validations;
import static windows.menu.mainPanel;

/**
 *
 * @author Emmanuel
 */
public class Empleados extends javax.swing.JPanel {

    /**
     * Stored Procedures candidatos
     * 
     * SP_Show_Candidatos
     * SP_Insert_Candidato
     * SP_Delete_Candidato
     * SP_Update_Candidato
     */
    public Empleados() {
        initComponents();
        CargarTabla("SELECT * FROM empleado");
        
    }
    
    
    public void CargarTabla(String query){
        empleadosTable.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = (DefaultTableModel) empleadosTable.getModel();
        empleadosTable.setRowHeight(20);
        //Comienza a contar 0 los renglones
        modelo.setRowCount(0);
        
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();

        ResultSet res = ConnectionDB.Query(query); 
        try{
            while(res.next()){
                JButton btnDelete = new JButton("Delete");
                btnDelete.setBackground(Color.red);
                btnDelete.setName("btnDelete");

                JButton btnUpdate = new JButton("Update");
                btnUpdate.setBackground(Color.green);   
                btnUpdate.setName("btnUpdate");
                
                JButton btnDeactivate = new JButton("Hire");
                btnDeactivate.setBackground(Color.BLUE);
                btnDeactivate.setName("btnHire");
                
                JButton btnPhone = new JButton("Phone");
                btnPhone.setName("btnPhone");
                
                JButton btnEmail = new JButton("Email");
                btnEmail.setName("btnEmail");
                
                JButton btnContact = new JButton("Contact");
                btnContact.setName("btnContact");
                
                Vector v = new Vector();
                //data user
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));
                v.add(res.getString(6));
                
                //contact, add email and phone
                v.add(btnEmail);
                v.add(btnPhone);
                v.add(btnContact);
                //delete, hire and update
                v.add(btnDelete);
                v.add(btnUpdate);
                v.add(btnDeactivate);
                
                modelo.addRow(v);

                empleadosTable.setModel(modelo);
            }
        }
        catch(SQLException e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombre = new javax.swing.JTextPane();
        registerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        empleadosTable = new javax.swing.JTable();
        buscarIdTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buscarID = new javax.swing.JButton();
        buscarNombreTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buscarNombre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showAllUsersBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        app = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        apm = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        expLab = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        expSal = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        puesto = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setBackground(new java.awt.Color(153, 153, 255));
        Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        Table.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 60, -1, -1));

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(nombre);

        Table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 80, 260, -1));

        registerButton.setText("Register");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        registerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerButtonKeyPressed(evt);
            }
        });
        Table.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 370, -1, -1));

        empleadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido P", "Apellido M", "RFC", "Email", "Phone", "Contact", "Update", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empleadosTable.getTableHeader().setReorderingAllowed(false);
        empleadosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(empleadosTable);
        if (empleadosTable.getColumnModel().getColumnCount() > 0) {
            empleadosTable.getColumnModel().getColumn(0).setResizable(false);
            empleadosTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            empleadosTable.getColumnModel().getColumn(1).setResizable(false);
            empleadosTable.getColumnModel().getColumn(2).setResizable(false);
            empleadosTable.getColumnModel().getColumn(3).setResizable(false);
            empleadosTable.getColumnModel().getColumn(4).setResizable(false);
            empleadosTable.getColumnModel().getColumn(5).setResizable(false);
            empleadosTable.getColumnModel().getColumn(5).setPreferredWidth(8);
            empleadosTable.getColumnModel().getColumn(6).setResizable(false);
            empleadosTable.getColumnModel().getColumn(6).setPreferredWidth(8);
            empleadosTable.getColumnModel().getColumn(7).setResizable(false);
            empleadosTable.getColumnModel().getColumn(7).setPreferredWidth(8);
            empleadosTable.getColumnModel().getColumn(8).setResizable(false);
            empleadosTable.getColumnModel().getColumn(8).setPreferredWidth(8);
            empleadosTable.getColumnModel().getColumn(9).setResizable(false);
            empleadosTable.getColumnModel().getColumn(9).setPreferredWidth(8);
        }

        Table.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1350, 260));

        buscarIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdTxtActionPerformed(evt);
            }
        });
        buscarIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarIdTxtKeyPressed(evt);
            }
        });
        Table.add(buscarIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 196, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Buscar Empleado por ID");
        Table.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        buscarID.setText("Buscar");
        buscarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarIDMouseClicked(evt);
            }
        });
        Table.add(buscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        Table.add(buscarNombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 200, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Buscar Empleado por nombre");
        Table.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        buscarNombre.setText("Buscar");
        buscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarNombreMouseClicked(evt);
            }
        });
        Table.add(buscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Empleados Activos");
        Table.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, 30));

        showAllUsersBtn.setText("Mostrar Todos");
        showAllUsersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllUsersBtnMouseClicked(evt);
            }
        });
        Table.add(showAllUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, 120, -1));

        app.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(app);

        Table.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, 260, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Apellido Paterno");
        Table.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 110, -1, -1));

        apm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apmKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(apm);

        Table.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 260, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Apellido Materno");
        Table.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, -1, -1));

        expLab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expLabKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(expLab);

        Table.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, 260, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Experiencia  Laboral");
        Table.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 210, -1, -1));

        expSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expSalKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(expSal);

        Table.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, 260, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Expectativa Salarial");
        Table.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, -1, -1));

        puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                puestoKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(puesto);

        Table.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 330, 260, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Puesto Deseado");
        Table.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
        Table.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, -1));

        add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char validate = evt.getKeyChar();

        if(!Character.isLetter(validate)){
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingresar solo letras");
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        //Register new user
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();

        String username = this.nombre.getText();
        
        boolean exists = conexion.existingUser(username);


    }//GEN-LAST:event_registerButtonActionPerformed

    
    
    private void empleadosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosTableMouseClicked

        int column = empleadosTable.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/empleadosTable.getRowHeight();

        if(row < empleadosTable.getRowCount() && row >= 0 && column<empleadosTable.getColumnCount() && column>=0){
            Object  value = empleadosTable.getValueAt(row, column);
            Object id = empleadosTable.getValueAt(row, 0);
            int id_User = (int) id;
            if(value instanceof JButton){
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                switch (boton.getName()) {
                    case "btnDelete":
                        {
                            //Query para borrar
                            int option = JOptionPane.showConfirmDialog(null, "Do you really want to delete this user?",
                                    "Warning", JOptionPane.YES_NO_OPTION);
                            if(option == JOptionPane.YES_OPTION){
                                ConnectionDB.deleteApplicantId(id_User);
                                CargarTabla("SP_Show_Candidatos");
                            }       
                            break;
                        }
                    case "btnUpdate":
                        String nname = (String) empleadosTable.getValueAt(row, 1);
                        String nlastn = (String) empleadosTable.getValueAt(row, 2);
                        String nlastnm = (String) empleadosTable.getValueAt(row, 3);
                        String nexLab = (String) empleadosTable.getValueAt(row, 4);
                        int nexpSal = (int) empleadosTable.getValueAt(row, 5);
                        String puestoP = (String) empleadosTable.getValueAt(row, 6);
                        ConnectionDB.updateApplicant(nname, nlastn, nlastnm, nexLab, nexpSal, puestoP, id_User);
                        CargarTabla("SP_Show_Candidatos");
                        break;
                    case "btnHire":
                        {
                            //query desactivar user
                            int option = JOptionPane.showConfirmDialog(null, "Do you really want to hire this applicant?",
                                    "Warning", JOptionPane.YES_NO_OPTION);
                            if(option == JOptionPane.YES_OPTION){                                
                                ConnectionDB.changeStatus(id_User);
                                CargarTabla("SP_Show_Candidatos");
                                
                            }       break;
                        }
                        
                    case "btnPhone":
                    {
                        JFrame frame = new JFrame("Agregar Telefono");
                        JPanel pane = new JPanel();
                        pane.setLayout(new GridLayout(0, 2, 2, 2));
                        
                        JTextField phoneN = new JTextField(10);
                        JTextField desc = new JTextField();
                        JTextField ext = new JTextField();
                        
                        pane.add(new JLabel("Teléfono: "));
                        pane.add(phoneN);
                        
                        pane.add(new JLabel("Extensión: "));
                        pane.add(ext);
                        
                        pane.add(new JLabel("Descripción: "));
                        pane.add(desc);
                        
                        int option = JOptionPane.showConfirmDialog(frame, pane, "Añadir teléfono", JOptionPane.OK_OPTION);
                        
                        if(option==JOptionPane.OK_OPTION){
                            String numeroTel = phoneN.getText();
                            String descTel = desc.getText();
                            String extension = ext.getText();
                            
                            if(Validations.numericPhoneNumber(numeroTel)){
                                ConnectionDB.insertPhone(numeroTel, extension, descTel);   
                                ConnectionDB.phoneCandidato(id_User);
                            }
                        }
                        break;
                    }
                    case "btnEmail":
                    {
                        JFrame frame = new JFrame("Agregar Email");
                        JPanel pane = new JPanel();
                        pane.setLayout(new GridLayout(0, 2, 2, 2));
                        
                        JTextField email = new JTextField();
                        JTextField desc = new JTextField();
                        
                        pane.add(new JLabel("Email: "));
                        pane.add(email);
 
                        pane.add(new JLabel("Descripción: "));
                        pane.add(desc);
                        
                        int option = JOptionPane.showConfirmDialog(frame, pane, "Añadir Email", JOptionPane.OK_OPTION);
                        
                        if(option==JOptionPane.OK_OPTION){
                            String mEmail = email.getText();
                            String mDesc = desc.getText();
                            
                            if(Validations.validateEmail(mEmail)){
                                ConnectionDB.insertEmail(mEmail, mDesc);   
                                ConnectionDB.emailCandidato(id_User);
                            }
                        } 
                        break;
                    }
                    case "btnContact":
                    {
                        
                        break;
                    }
                    default:
                        break;
                }
            }
            
        }
    }//GEN-LAST:event_empleadosTableMouseClicked

    private void buscarIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarIdTxtActionPerformed

    private void buscarIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarIDMouseClicked

        int id_user = Integer.parseInt(buscarIdTxt.getText());
        String consulta = "SELECT * FROM users WHERE id_user = "+id_user;
        CargarTabla(consulta);
    }//GEN-LAST:event_buscarIDMouseClicked

    private void buscarIdTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarIdTxtKeyPressed
       char validate = evt.getKeyChar();

    //        if(!Character.isDigit(validate)){
    //            getToolkit().beep();
    //            evt.consume();
    //            JOptionPane.showMessageDialog(null, "Ingresar solo números");
    //        }
    }//GEN-LAST:event_buscarIdTxtKeyPressed

    private void showAllUsersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllUsersBtnMouseClicked
        CargarTabla("SP_Show_Candidatos");
    }//GEN-LAST:event_showAllUsersBtnMouseClicked

    private void buscarNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarNombreMouseClicked
        String username = buscarNombreTxt.getText();
        String consulta = "SP_Search_User_Like '"+username+"'";
        
        buscarIdTxt.setText("");
        buscarNombreTxt.setText("");
        CargarTabla(consulta);
    }//GEN-LAST:event_buscarNombreMouseClicked

    private void appKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_appKeyTyped

    private void apmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apmKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_apmKeyTyped

    private void expLabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expLabKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_expLabKeyTyped

    private void expSalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expSalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_expSalKeyTyped

    private void puestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puestoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoKeyTyped

    private void registerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonKeyPressed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        ConnectionDB conexion = new ConnectionDB();
        conexion.getConnection();
        
        String name = nombre.getText();
        String lastn = app.getText();
        String lastnm = apm.getText();
        String expLabo = expLab.getText();
        String salario = expSal.getText();
        String puestoP = puesto.getText();
        
        if(Validations.length50Empty(name) && Validations.length50Empty(lastn) &&
                Validations.length50Empty(lastnm) && Validations.length50Empty(expLabo)
                && Validations.length50Empty(salario) && Validations.length50Empty(puestoP)){
            conexion.createApplicant(name, lastn, lastnm, expLabo, salario, puestoP);
            CargarTabla("SP_Show_Candidatos");
            nombre.setText("");
            app.setText("");
            apm.setText("");
            expLab.setText("");
            expSal.setText("");
            puesto.setText("");
        }

        
        
    }//GEN-LAST:event_registerButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Table;
    private javax.swing.JTextPane apm;
    private javax.swing.JTextPane app;
    private javax.swing.JButton buscarID;
    private javax.swing.JTextField buscarIdTxt;
    private javax.swing.JButton buscarNombre;
    private javax.swing.JTextField buscarNombreTxt;
    private javax.swing.JTable empleadosTable;
    private javax.swing.JTextPane expLab;
    private javax.swing.JTextPane expSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane nombre;
    private javax.swing.JTextPane puesto;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showAllUsersBtn;
    // End of variables declaration//GEN-END:variables
}
