/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Emmanuel
 */
public class menu extends javax.swing.JFrame {

    
    public menu() {
        initComponents();
        
        this.setLocationRelativeTo(null);   
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/tecsosLogo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        Users = new javax.swing.JMenu();
        AddUser = new javax.swing.JMenuItem();
        DeleteUser = new javax.swing.JMenuItem();
        EditUser = new javax.swing.JMenuItem();
        SearchUser = new javax.swing.JMenuItem();
        Applicants = new javax.swing.JMenu();
        AddApplicant = new javax.swing.JMenuItem();
        DeleteApplicant = new javax.swing.JMenuItem();
        EditApplicant = new javax.swing.JMenuItem();
        SearchApplicant = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        Users.setText("Users");
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        AddUser.setText("Add User");
        AddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserMouseClicked(evt);
            }
        });
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });
        Users.add(AddUser);

        DeleteUser.setText("Delete User");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });
        Users.add(DeleteUser);

        EditUser.setText("Edit User");
        Users.add(EditUser);

        SearchUser.setText("Search User");
        SearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserActionPerformed(evt);
            }
        });
        Users.add(SearchUser);

        menuBar.add(Users);

        Applicants.setText("Applicants");

        AddApplicant.setText("Add Applicant");
        Applicants.add(AddApplicant);

        DeleteApplicant.setText("Delete Applicant");
        Applicants.add(DeleteApplicant);

        EditApplicant.setText("Edit Applicant");
        EditApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditApplicantActionPerformed(evt);
            }
        });
        Applicants.add(EditApplicant);

        SearchApplicant.setText("Search Applicant");
        Applicants.add(SearchApplicant);

        menuBar.add(Applicants);

        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        menuBar.add(Exit);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        AddUser adduser = new AddUser();
        adduser.setSize(710, 450);
        adduser.setLocation(5,5);
        
        mainPanel.removeAll();
        mainPanel.add(adduser, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();        
    }//GEN-LAST:event_AddUserActionPerformed

    private void SearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchUserActionPerformed

    private void EditApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditApplicantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditApplicantActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void AddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserMouseClicked
        
    }//GEN-LAST:event_AddUserMouseClicked

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        
    }//GEN-LAST:event_UsersActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        
    }//GEN-LAST:event_DeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddApplicant;
    private javax.swing.JMenuItem AddUser;
    private javax.swing.JMenu Applicants;
    private javax.swing.JMenuItem DeleteApplicant;
    private javax.swing.JMenuItem DeleteUser;
    private javax.swing.JMenuItem EditApplicant;
    private javax.swing.JMenuItem EditUser;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenuItem SearchApplicant;
    private javax.swing.JMenuItem SearchUser;
    private javax.swing.JMenu Users;
    public static javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
