/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.BorderLayout;
import static windows.menu.mainPanel;

/**
 *
 * @author Emmanuel
 */
public class usersMenu extends javax.swing.JPanel {

    /**
     * Creates new form usersMenu
     */
    public usersMenu() {
        initComponents();
        
        //To set the table
        ActiveUsersTable aut = new ActiveUsersTable();
        aut.setSize(600, 290);
        aut.setLocation(5,5);
        activeUsersTable.add(aut, BorderLayout.CENTER);
        activeUsersTable.revalidate();
        activeUsersTable.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttons = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFields = new javax.swing.JPanel();
        activeUsersTable = new javax.swing.JPanel();
        inactiveUsersTable = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttons.setBackground(new java.awt.Color(204, 255, 255));
        buttons.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        buttons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setForeground(java.awt.SystemColor.activeCaption);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_user.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buttons.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jButton1.setForeground(java.awt.SystemColor.activeCaption);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_user.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        buttons.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButton3.setForeground(java.awt.SystemColor.activeCaption);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_user.png"))); // NOI18N
        buttons.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButton4.setForeground(java.awt.SystemColor.activeCaption);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_user.png"))); // NOI18N
        buttons.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add User");
        buttons.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Delete User");
        buttons.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Edit User");
        buttons.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Search User");
        buttons.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        add(buttons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 280));

        txtFields.setBackground(new java.awt.Color(51, 153, 255));
        txtFields.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout txtFieldsLayout = new javax.swing.GroupLayout(txtFields);
        txtFields.setLayout(txtFieldsLayout);
        txtFieldsLayout.setHorizontalGroup(
            txtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        txtFieldsLayout.setVerticalGroup(
            txtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        add(txtFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 600, 280));

        activeUsersTable.setBackground(new java.awt.Color(102, 204, 255));
        activeUsersTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout activeUsersTableLayout = new javax.swing.GroupLayout(activeUsersTable);
        activeUsersTable.setLayout(activeUsersTableLayout);
        activeUsersTableLayout.setHorizontalGroup(
            activeUsersTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        activeUsersTableLayout.setVerticalGroup(
            activeUsersTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        add(activeUsersTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 600, 290));

        inactiveUsersTable.setBackground(new java.awt.Color(0, 204, 204));
        inactiveUsersTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout inactiveUsersTableLayout = new javax.swing.GroupLayout(inactiveUsersTable);
        inactiveUsersTable.setLayout(inactiveUsersTableLayout);
        inactiveUsersTableLayout.setHorizontalGroup(
            inactiveUsersTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        inactiveUsersTableLayout.setVerticalGroup(
            inactiveUsersTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        add(inactiveUsersTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 280, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddUserPane addUser = new AddUserPane();
        addUser.setSize(710, 450);
        addUser.setLocation(5,5);
        
        txtFields.removeAll();
        txtFields.add(addUser, BorderLayout.CENTER);
        txtFields.revalidate();
        txtFields.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DeleteUserPane deleteUser = new DeleteUserPane();
        deleteUser.setSize(710, 450);
        deleteUser.setLocation(5,5);
        
        txtFields.removeAll();
        txtFields.add(deleteUser, BorderLayout.CENTER);
        txtFields.revalidate();
        txtFields.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activeUsersTable;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel inactiveUsersTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel txtFields;
    // End of variables declaration//GEN-END:variables
}
